import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import ProfileCard from "./../components/profileCard"
import SideBar from "./../components/sideBar";
import "./globals.css";

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Specializations V1",
  description: "Generated by create next app",
  keywords: ["Specializations", "Hire me", "profile", "skills"],
  icons: {
    icon: "/next.svg",
    shortcut: "/shortcut.png",
  },
  authors: [
    {
      name: "Dusit65",
      url: "https://github.com/Dusit65",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libreFranklin.className} bg-neutral-800 px-40`}>
        <div className="flex w-full min-h-screen  py-1 space-x-4">
          {/* Sidebar and ProfileCard are always present,
          positioned at the left and right as per the image. */}
          <div className="flex-shrink-0 my-auto border-2 rounded-2xl border-neutral-500 ">
            <ProfileCard />
          </div>
          <main className="flex-grow pt-30    overflow-auto justify-center">
            {children}
          </main>
          <div className="flex-shrink-0 flex flex-col my-auto border-2 rounded-4xl border-neutral-500">
            <SideBar />
          </div>
        </div>
      </body>
    </html>
  );
}
